### ISSUE TITLE
Fails to build with `react-scripts build `

### ISSUE THREAD

**Issue by akollegger** [xpl/string.ify#4]
Using `string.ify` in a `create-react-app` project fails the `react-scripts build`, because the `printable-characters` dependency can't be minified.

Build snippet...

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/printable-characters/build/printable-characters.js:14 

Read more here: http://bit.ly/2tRViJ9
```

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by akollegger** [comment]
OK, and realizing now that `printable-characters` is also yours @xpl , should this issue be pushed there?

**Comment by kroitor** [comment]
Hi, @akollegger! See this comment by @xpl https://github.com/ccxt-dev/ccxt/issues/299#issuecomment-335504025. It's practically the same issue and a solution for create-react-app is also there. Hope it helps.

**Comment by akollegger** [comment]
Ah, ok. Makes sense. Thank you!

**Comment by xpl** [comment]
@akollegger In fact, it's better to solve the problem by pre-transpiling everything down to plain ES5 in these modules (I will do that in the near future). But, still, it's a shame that some popular tools like UglifyJS (which, btw, is the cause of the error you experience) require everything be transpiled to ES5 while all modern browsers already provide support for ES6 out of the box...
