### ISSUE TITLE
[Feature request]: Option to print without alignment.

### ISSUE THREAD

**Issue by thezimmee** [xpl/string.ify#6]
First off, thank you for this package. Its configurability is wonderful, just what I needed. My only request is to make an option to pretty print, but without the alignment. Currently, to my knowledge, when the `pretty` option is on it aligns object properties, but when it's off it prints everything on a single line, so everything is clustered together and less readable. Any chance of printing on separate lines without the colon alignment?

Thanks again, I appreciate the work on this!

**Comment by xpl** [comment]
> Any chance of printing on separate lines without the colon alignment?

Yeah, why not. Can you provide a specific example of the formatting you want (to be used as a reference)? I'll figure how to make it possible.

**Comment by thezimmee** [comment]
I appreciate it! I would love to see something like this:

```js
{
  string: "one",
  one: 1,
  deep: {
    one: {
      two: {
        three: "three",
        four: 4,
        five: "five",
        six: { another: "one", same: "line" },
        seven: 7,
        eight: 8
      }
    }
  }
}
```

or brackets on the same line:

```js
{ string: "one",
  one: 1,
  deep: {
    one: {
      two: {
        three: "three",
        four: 4,
        five: "five",
        six: { another: "one", same: "line" },
        seven: 7,
        eight: 8
} } } }
```

I prefer the defaults tab at 2 spaces, but maybe that can be configurable too.

**Comment by xpl** [comment]
@thezimmee Please see the updated documentation:

https://github.com/xpl/string.ify/blob/master/README.md#pretty-printing

Basically, there are three new config options:

```javascript
{
     rightAlignKeys: true,
     fancy: true,
     indentation: '    ' // applies only if fancy=false
}
```

Default rendering:

```
{ obj: [ { someLongPropertyName: 1,
                   propertyName: 2,
                    anotherProp: 4,
                      moreProps: 5  },
         { propertyName: { someVeryLongPropertyName:  true,
                                                qux:  6,
                                                zap: "lol"  } } ] }
```

With `rightAlignKeys: false`:

```
{ obj: [ { someLongPropertyName: 1,
           propertyName: 2,
           anotherProp: 4,
           moreProps: 5             },
         { propertyName: { someVeryLongPropertyName: true,
                           qux: 6,
                           zap: "lol"                      } } ] }
```

With `fancy: false`:

```
{
    obj: [
        {
            someLongPropertyName: 1,
            propertyName: 2,
            anotherProp: 4,
            moreProps: 5
        },
        {
            propertyName: {
                someVeryLongPropertyName: true,
                qux: 6,
                zap: "lol"
            }
        }
    ]
}
```

In `fancy: false` mode, you can change the indentation width to 2 spaces:

```
stringify.configure ({ fancy: false, indentation: '  ' }) (x)
```
```
{
  obj: [
    {
      someLongPropertyName: 1,
      propertyName: 2,
      anotherProp: 4,
      moreProps: 5
    },
    {
      propertyName: {
        someVeryLongPropertyName: true,
        qux: 6,
        zap: "lol"
      }
    }
  ]
}
```

Let me know if that helps.

**Comment by thezimmee** [comment]
@xpl You are wonderful. Works perfectly. Thank you so much!!
